import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { Data } from './api/hello'

export default function Home() {
  const [title, setTitle] = useState('')

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    fetch('/api/hello?' + new URLSearchParams({ url: params.get('url') || ''}))
      .then(res => {
        res.json()
          .then((data: Data) => setTitle(data.title))
          .catch(console.error)
      })
      .catch(console.error)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {title}
      </main>
    </>
  )
}
